Name: Ronit Mehta PRN: 25070123094

AIM: Study of Numpy Library

Numpy:

Create Arrays

Performs numerical operation

In [66]:
#why numpy?
## It is faster
## It is used for numerical operations
## base for pandas

In [67]:
#declaration of numpy
import numpy as np

a = np.array([1,10,20,30,40,50,500])
b = np.array([[1,2,3],[4,5,6]])

print(a)
print(b)


[  1  10  20  30  40  50 500]
[[1 2 3]
 [4 5 6]]


In [68]:
#dimension of array

print(a.ndim)
print(b.ndim)

1
2


In [69]:
#shape of matrix
print(a.shape)
print(b.shape)

(7,)
(2, 3)


In [77]:
#printing datatype of a
print(a.dtype)
print(b.dtype)

int64
int64


In [71]:
print(np.zeros((2,3)))
print(np.ones((2,3)))

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [72]:
print(np.eye((3)))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [73]:
print(np.arange(1,10,2))

[1 3 5 7 9]


In [74]:
print(np.linspace(0,1,4))

[0.         0.33333333 0.66666667 1.        ]


In [75]:
print(a)
print(b)

print(b*2)
print(a+5)

[  1  10  20  30  40  50 500]
[[1 2 3]
 [4 5 6]]
[[ 2  4  6]
 [ 8 10 12]]
[  6  15  25  35  45  55 505]


In [76]:
print(np.mean(a))
print(np.median(a))
print(np.max(a))
print(np.min(a))
print(np.sum(a))

93.0
30.0
500
1
651
